# Generated by Django 3.1.5 on 2021-01-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName_text', models.CharField(max_length=20)),
                ('lastName_text', models.CharField(max_length=20)),
                ('fullName_text', models.CharField(max_length=50)),
                ('NickName_text', models.CharField(max_length=10)),
                ('phone_field', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('aboutMe', models.TextField()),
                ('line', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_field', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.person')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectLink', models.URLField()),
                ('description', models.TextField()),
                ('workDuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.workduration')),
            ],
        ),
        migrations.CreateModel(
            name='SocialContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.person')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_text', models.CharField(max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.person')),
            ],
        ),
        migrations.CreateModel(
            name='FrontendSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_text', models.CharField(max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.person')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_field', models.EmailField(max_length=254)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.person')),
            ],
        ),
        migrations.CreateModel(
            name='BackendSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_text', models.CharField(max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.person')),
            ],
        ),
    ]
