# Generated by Django 3.1.5 on 2021-01-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgrammingLang',
            new_name='ProgrammingLanguage',
        ),
        migrations.AlterField(
            model_name='person',
            name='aboutMe',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_field',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
